### ISSUE TITLE
Allow for user-defined reconnect interval

### ISSUE THREAD

**Issue by benruijl** [ekulyk/PythonPusherClient#10]
It is currently impossible to set a user-defined reconnect interval, since the variable self.reconnect_interval is set to the function argument of the reconnect() function every time it is called. 

The quickest way to implement this feature is to let the default value of reconnect_interval in the reconnect function point to an instance variable.

**Comment by ekulyk** [comment]
Support for user-defined reconnect interval added in changeset: 05fed1f82552924a32617549de03e4a80c637fcf
