### ISSUE TITLE
Error messages started yesterday (no code changes)

### ISSUE THREAD

**Issue by jperenia** [ekulyk/PythonPusherClient#4]
I've been using your PythonPusherClient module and as of yesterday it broke for no known reason.  None of the code I use has been changed, it just broke.

Connection: Message - {"event":"pusher:error","data":{"code":4005,"message":"Path not found"}}
Connection: Unhandled event
Connection: Error - 
Connection: Connection closed
Attempting to connect again in 10 seconds.

**Comment by leggetter** [comment]
This means that the URL that's being used to connect to Pusher is incorrect. This can happen if an app_key is not being correctly supplied and therefore the URL doesn't correctly identify an application.

_Note: I don't know this library, so this is just a best guess_

**Comment by jperenia** [comment]
Thanks, the URL actually had 2 forward slashes instead of 1 forward slash which was causing it to break.  Thanks for the tip!
