### ISSUE TITLE
"Pusher protocol versions <= 3 have been deprecated. Support will be removed after November 2013"

### ISSUE THREAD

**Issue by adamyeats-zz** [ekulyk/PythonPusherClient#7]
Hey @ekulyk, Adam from Pusher here.

We've been contacted by several of our customers as this library supports a version of our protocol that is  <= version 3, and we are sending warnings out to customers warning that we are going to be deprecating these versions of the API shortly. We plan to finish deprecating these versions before the New Year.

In order to keep this library usable for you and your users, could you please ensure that the library is upgraded to a later version of the protocol (preferably version 6)? Please contact me directly if you'd like me to assist you in any way with this. :)

**Comment by ekulyk** [comment]
Hey Adam,

I've done some work updating it to version 6 of the protocol.

In brief:
- now respond to "pusher:ping" events on the pusher protocol level (http://pusher.com/docs/pusher_protocol#ping-pong)
- now handles "pusher:error" sent from pusher (http://pusher.com/docs/pusher_protocol#error-codes)

I goofed up when pushing and meant to have it in a separate branch for the time being, but it ended up in master.  Whoops.
